"""initial

Revision ID: f9e603a82b9b
Revises:
Create Date: 2026-09-14 15:41:54.069333

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f9e603a82b9b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
